### PR TITLE
Fix updating devel packages when make dependencies are not installed

### LINKED ISSUE #155: Update with option --devel and makedepends
When performing yaourt -Syua --devel, some packages are not updated and return error "==> ERROR: Could not resolve all dependencies."

For example freshplayerplugin-git needs ragel as a makedepends, thus it is needed only to compile and ragel can be removed after installation. The expected behaviour would be to install this dependency with option --asdeps as it is done when you compile a package with option "-S".

### PR DESCRIPTION
**Pull request by larchunix**
Fix #155

### CODE REVIEW

**Comment by oryband** [comment]
:+1: please merge i can't update half of my system because of this

**Comment by Skunnyk** [comment]
Hm, nop.
The problem is that yaourt does not check for missing makedepend on -Syua --devel. 
Your patch (-d) only disable dependancie check on makepkg.

For example, remove git from your system.

Then run yaourt -Syua --devel 
You'll have some -git package to upgrade :

```
[...]

==> elementary-xfce-icons-git dependencies:
 - adwaita-icon-theme (already installed)
 - gnome-icon-theme (already installed)
 - git (package found) [makedepend]


[...]

==> Continue building elementary-xfce-icons-git ? [Y/n]
==> ---------------------------------------------------
==> 
==> Building and installing package
==> Making package: elementary-xfce-icons-git 0.7.r9.gb19b0b2-1 (Fri Nov  6 14:33:13 CET 2015)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
  -> Cloning elementary-xfce git repo...
/usr/bin/makepkg: line 542: git: command not found
==> ERROR: Failure while downloading elementary-xfce git repo
    Aborting...
```

**Comment by larchunix** [comment]
> The problem is that yaourt does not check for missing makedepend on -Syua --devel.

Before installing make dependencies, yaourt checks if a new version of the devel package is available:
 - if we don't have the latest version of the package, yaourt installs make dependencies and then builds the package,
 - if we already have the latest version of the package yaourt does nothing.

I wanted to keep this workflow because it avoids installing make dependencies if they are not needed.

> Your patch (-d) only disable dependancie check on makepkg.

Yaourt retrieves the latest version of a devel package using the `pkgver()` function from the `PKGBUILD`. This function needs a copy of the source repository and yaourt uses `makepkg -o` to extract it. At this point, makepkg needs the VCS to do the extraction however all other make dependencies are useless. With my patch, `makepkg -o -d` doesn't fail even if make dependencies are not installed (they will be installed if needed, after comparing current and latest versions).  

> For example, remove git from your system.

Obviously, if you remove the VCS, `makepkg -o` will fail to extract the source repository and my patch doesn't handle this case. I can modify my patch to install the relevant VCS just before calling `makepkg -o` but IMHO it is not worth it. It should be expected not being able to build a devel package if the corresponding VCS is not installed.

What is your opinion ?

**Comment by Skunnyk** [comment]
My bad, that git thing was a bad test/example (I hadn't any devel package to update when I tested it…).
So yes, you are right, ```pkgver()``` check does not need makedepend to be installed, and your patch works, by installing makedepend only at build time :)

**Pull request merged**
