### PR TITLE
Resolve the "Empty 'required by' message" issue

### LINKED ISSUE #39: Empty 'required by' message when dependency provided by other package
E.g. I want to update skype and it has new dependency, `lib32-pulseaudio`:

    ==> Software upgrade (new version) :
    multilib/skype            4.2.0.13-4 -> 4.3.0.37-1

    ==> New package :
    multilib/lib32-json-c     0.12-1     (required by lib32-libpulse)
    multilib/lib32-libasyncns 0.8-6      (required by lib32-libpulse)
    multilib/lib32-libcap     2.24-1     (required by lib32-libpulse)
    multilib/lib32-libxtst    1.2.2-1    (required by lib32-libpulse)
    multilib/lib32-libogg     1.3.1-1    (required by lib32-flac)
    multilib/lib32-flac       1.3.0-1    (required by lib32-libsndfile)
    multilib/lib32-libvorbis  1.3.4-1    (required by lib32-libsndfile)
    multilib/lib32-libsndfile 1.0.25-2   (required by lib32-libpulse)
    multilib/lib32-libpulse   5.0-1      (required by -)

The thing is that repository doesn't contains `lib32-pulseaudio`, but it has `lib32-libpulse` which provides that package.

### PR DESCRIPTION
**Pull request by f2404**
Fix #39

### CODE REVIEW

**Comment by larchunix** [comment]
Patch tested by upgrading from `ffmpeg-1:2.8.1-2` to `ffmpeg-1:2.8.1-3` and it worked fine in my case.

    $ yaourt -Su
    ==> Package upgrade only (new release):
    extra/ffmpeg   1:2.8.1-2 2 -> 3

    ==> New package :
    extra/vid.stab 1.1-1     (required by ffmpeg)

    ==> Continue upgrade ? [Y/n]
    ...

The package `vid.stab` was correctly installed as a dependency

    $ pacman -Qi vid.stab
    Name           : vid.stab
    ...
    Install Reason : Installed as a dependency for another package
    ...

**Comment by f2404** [comment]
Hmm, that's weird - I'm getting ```vid.stab``` "Explicitly installed" when running ```yaourt -Syu --aur```. And I'm getting it "Installed as a dependency" when running ```yaourt -Syu```.

**Comment by larchunix** [comment]
Really weird - I just tested with and without `--aur` and I got "Installed as a dependency" in both cases.

**Comment by Skunnyk** [comment]
Hm, just tested and it seems that it works, with -Su and -Su --aur : 
```
extra/vid.stab                            1.1-1                  (required by ffmpeg)
```

**Comment by f2404** [comment]
@Skunnyk ok then, will you merge it?

**Pull request merged**
