### PR TITLE
Improve support of --assume-installed

### LINKED ISSUE #175: assume-installed is not working?
I have Oracle's JDK installed manually and added to the `PATH`, so `java` is available in the system. Now I want to install [fritzing](https://aur.archlinux.org/packages/fritzing), which requires Java to run:

```shell
pacman --version                                                                                                                                                   

 .--.                  Pacman v4.2.1 - libalpm v9.0.1
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2014 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
 '--'
                       This program may be freely redistributed under
                       the terms of the GNU General Public License.

yaourt --version                                                                                                                                                
yaourt 1.7

yaourt -S fritzing                                                                                                                                              

...

==> Continue building fritzing ? [Y/n]
==> ----------------------------------
==> 
==> Building and installing package
==> Install or build missing dependencies for fritzing:
:: There are 2 providers available for java-environment:
:: Repository extra
   1) jdk7-openjdk  2) jdk8-openjdk

Enter a number (default=1):
```

 I do not want to install neither `jdk7-openjdk` nor `jdk8-openjdk` which both provide `java-environment`. So I'm trying to use `--assume-installed` option:

```shell
java -version                                                                                                                                                   
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

yaourt -S fritzing --assume-installed jdk8-openjdk
error: no targets specified (use -h for help)

yaourt --assume-installed jdk8-openjdk -S fritzing
error: no targets specified (use -h for help)

yaourt -S --assume-installed java-environment fritzing
error: no targets specified (use -h for help)

yaourt -S --assume-installed java-environment -- fritzing                                                                                                       
error: no targets specified (use -h for help)
```

All that commands failed. How can I assume that Java is already present on my machine?

### PR DESCRIPTION
**Pull request by larchunix**
Feedback and regression tests welcome.

### CODE REVIEW

**Comment by madhead** [comment]
Testing this with Fritzing (as in #175): 

```
┌[madhead@madhead-linux:~/Projects/yaourt/src]
└─130! $ /usr/local/bin/yaourt -S --assume-installed java-environment fritzing
==> WARNING: problem in pkgbuild.sh library

==> Downloading fritzing PKGBUILD from AUR...
x .SRCINFO
x PKGBUILD
x fritzing.install
x fritzing.xml

...

== Starting build()...
/usr/lib/qt/bin/uic: error while loading shared libraries: libicui18n.so.55: cannot open shared object file: No such file or directory
/usr/lib/qt/bin/uic: error while loading shared libraries: libicui18n.so.55: cannot open shared object file: No such file or directory
/usr/lib/qt/bin/uic: error while loading shared libraries: libicui18n.so.55: cannot open shared object file: No such file or directory
/usr/lib/qt/bin/uic: error while loading shared libraries: libicui18n.so.55: cannot open shared object file: No such file or directory
make -f Makefile.Release
make[1]: Entering directory '/tmp/yaourt-tmp-grant/aur-fritzing/src/fritzing-app-0.9.2b'
/usr/lib/qt/bin/uic src/program/consolewindow.ui -o ui_consolewindow.h
/usr/lib/qt/bin/uic: error while loading shared libraries: libicui18n.so.55: cannot open shared object file: No such file or directory
Makefile.Release:2639: recipe for target 'ui_consolewindow.h' failed
make[1]: *** [ui_consolewindow.h] Error 127
make[1]: Leaving directory '/tmp/yaourt-tmp-grant/aur-fritzing/src/fritzing-app-0.9.2b'
Makefile:38: recipe for target 'release' failed
make: *** [release] Error 2
== ERROR: A failure occurred in build().

I did some searching the package that owns that shared lib is called "icu". I realized that the package wasn't even installed, so I installed it and fritzing built successfully.

Should "icu" be added as a dependency? I at least wanted to let people know in case anyone else runs into this problem.

Bevan commented on 2015-04-09 22:33 
@Smitty: icu is a dependency of qt5-base and therefore indirectly also of this package. No idea, how you could have ended up in that situation. Maybe a partial upgrade.

razer commented on 2016-01-16 14:06 
Please consider adding MIME type association ".fzz" during install cycle by applying this changes :

Add fritzing MIME xml descriptor to AUR/GIT repo:
http://s000.tinyupload.com/index.php?file_id=65578174977374662207

Patching the PKGBUILD file :
patch - http://s000.tinyupload.com/?file_id=53643455802935776672
entire PKGBUILD - http://s000.tinyupload.com/index.php?file_id=03641390728678636078

Bevan commented on 2016-01-30 10:55 
@razer: Thanks for the suggestion! I applied it alongside some additions.

fritzing 0.9.2b-2  (2016-01-30 10:50)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> n

==> fritzing dependencies:
 - desktop-file-utils (already installed)
 - python2 (already installed)
 - qt5-serialport (already installed)
 - qt5-svg (already installed)
 - shared-mime-info (already installed)
 - boost (already installed) [makedepend]
 - java-environment (package found)


==> Edit fritzing.install ? [Y/n] ("A" to abort)
==> --------------------------------------------
==> n

==> Continue building fritzing ? [Y/n]
==> ----------------------------------
==> 
==> Building and installing package
==> Install or build missing dependencies for fritzing:
resolving dependencies...
looking for conflicting packages...

Packages (5) java-environment-common-2-2  java-runtime-common-2-2  jre7-openjdk-7.u95_2.6.4-1  jre7-openjdk-headless-7.u95_2.6.4-1  jdk7-openjdk-7.u95_2.6.4-1

Total Download Size:   57.36 MiB
Total Installed Size:  96.86 MiB

:: Proceed with installation? [Y/n] n
==> Restart building fritzing ? [y/N]
==> ---------------------------------
==>
```

Still tries to download Java. Also asks for editing PKGBUILD during installation, originla `yaourt` doesn't do that.

**Comment by larchunix** [comment]
Damn, I read your issue too fast and didn't see you were building a package from AUR.

My patch works only for packages from repos and I'm afraid your issue cannot be solved only by changing `yaourt`.

Indeed, `makepkg` checks dependencies before building the package and to my knowledge there is no option equivalent to `--assume-installed` for `makepkg`.

IMHO, your best option is to edit the PKGBUILD before the build and remove `java-environment` dependency.

**Comment by madhead** [comment]
Great idea! I don't need to build / install it manually just comment one line in `PKGBUILD`. Thank you for your suggestion!

**Comment by madhead** [comment]
@larchunix, sorry to bother one more time, but how do I safe-delete the yaourt which I've build from your sources? Is there any command? Can do that by reading a list of files and deleting them manually, but looking for a better solution for future.

**Comment by f2404** [comment]
@madhead this depends on how you've installed, I guess. For example, if you built and installed it like a real package, then it'd be enough to just install original yaourt on top.

**Comment by larchunix** [comment]
@madhead, as the `Makefile` does not provide an `uninstall` target, you have to remove the files manually.

**Comment by f2404** [comment]
Your changes certainly make it work better with non-AUR packages:
```
$ ./yaourt.sh -S --assume-installed sdl_mixer freeciv
resolving dependencies...
looking for conflicting packages...

Packages (2) lua52-5.2.4-1  freeciv-2.5.1-1
```
vs
```
$ yaourt -S --assume-installed sdl_mixer freeciv
resolving dependencies...
looking for conflicting packages...

Packages (5) libmikmod-3.3.8-1  lua52-5.2.4-1  sdl_mixer-1.2.12-4  smpeg-0.4.5-2  freeciv-2.5.
```

GTM.

**Pull request merged**
