### PR TITLE
Use package-query to read licenses

### PR DESCRIPTION
**Pull request by f2404**

### CODE REVIEW

**Comment by larchunix** [comment]
Hum, why did you decide to use package-query for the license and not for the others fields ?

**Comment by f2404** [comment]
Hmm, I tried to adopt other fields from pacman, and it turned out that it's not a straight-forward task to read arrays into variables:
```bash
    read id votes outofdate maintainer last_mod popularity pkgbuild_url licenses \
        pkgver pkgdesc \
        < <(pkgquery -Aif '%i %w %o %m %L %p %u "%e" %V %d' "$pkgname")
```
So I'm thinking this PR should be discarded.

**Comment by f2404** [comment]
But it looks like I've found an issue when working on this.

**Comment by larchunix** [comment]
I suspect the space between each licenses.

You should probably use package-query with --delimiter and play with IFS, something like this:

    read id votes [...] licenses pkgver pkgdesc \
        < <(pkgquery --delimiter='|' -Aif '%i %w %o %m %L %p %u %e %V %d' "$pkgname")

    oldIFS=$IFS; IFS='|'
    licenses=(echo $licenses)
    IFS=$oldIFS

    ....

**Comment by f2404** [comment]
The `afx2usb-linux-git` issue has been fixed with this commit.
For `dnf, however, the version is weird; cannot tell what's the reason is:
```
$ yaourt -Si dnf
Repository     : aur
Name           : dnf
Version        : 1.1.6.1-1-1
```

**Comment by larchunix** [comment]
Both epoch and pkgrel are return by AUR:

    package-query -Aif '%v' fish-git
    2:2.2.0.r459.gf045d9b-1

We can probably simply use:

    aur_show_info "Version        " "$CGREEN$pkgver$C0"

**Comment by f2404** [comment]
Thanks - please see the latest commit.

**Comment by larchunix** [comment]
Works fine for me.

**Pull request merged**
