### PR TITLE
Add an option to update AUR packages only

### PR DESCRIPTION
**Pull request by larchunix**
This feature was requested in #68

### CODE REVIEW

**Comment by puckel** [comment]
I tried your patch, but it only works if I set "DETAILUPGRADE=0" in yaourtrc, by default this options is set to 1. Running the aur-only upgrade shows me the aur package, but after hitting Enter key, yaourt tries to upgrade all my system

**Comment by larchunix** [comment]
Thanks for testing.

I did more tests with `DETAILUPGRADE=0` and `DETAILUPGRADE=1` and both worked fine for me.

I don't understand what happens in your case.

**Comment by puckel** [comment]
With DETAILUPGRADE=1 :

```
yaourt -Syua --aur-only
 Foreign packages: - 14 / 14

==> Package upgrade only (new release):
[...]

==> Continue upgrade ? [Y/n]
==> [V]iew package detail   [M]anually select packages
==> --------------------------------------------------
==> Y
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Package (93)                        Old Version     New Version          Net Change  Download Size

[...]

Total Download Size:   231.87 MiB
Total Installed Size:  876.91 MiB
Net Upgrade Size:        6.03 MiB

:: Proceed with installation? [Y/n] 
```

With DETAILUPGRADE=0
```
yaourt -Syua --aur-only
 Foreign packages: - 14 / 14

AUR targets (4): ...

==> Proceed with upgrade?  [Y/n]
==> ----------------------------
==> Y
==> Downloading  PKGBUILD from AUR...
Cloning into '.'...
remote: Counting objects: 64, done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 64 (delta 30), reused 58 (delta 24)
[...]
```

**Comment by Skunnyk** [comment]
I have more or less the same behavior as @puckel : with -Syua --aur-only, it prints only aur package to update, but when i press Y, it try to upgrade system packages.

I know it's a wanted feature but I don't know if it's a good idea to update only aur packages. Arch way is to only support latest version (see https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported ), so if you only want to update AUR packages, it's a partial upgrade …

What do you think ?

**Comment by larchunix** [comment]
To tell the truth, I will never use this feature myself. The reason I implemented it was because several people requested it and I thought this simple patch was enough to do the trick (obviously I was wrong).

**Pull request closed without merging**
