### PR TITLE
Refactorize sysupgrade to improve customizepkg support

### LINKED ISSUE #51: yaourt -Syu bug when one package uses customizepkg
Doing a full upgrade with yaourt -Syu... if one of the packages that needs upgrading makes yaourt run customizepkg, when that is finished installing, it tries to install the uncustomized version afterwards.

### PR DESCRIPTION
**Pull request by larchunix**
Fix #51 btw.

### CODE REVIEW

**Comment by Skunnyk** [comment]
wow, thank you :)

**Comment by f2404** [comment]
I think it has added a space in the beginning of the line:
``` yaourt-git : (local=1.7.54.g5f4e94e-1 aur=1.6-1)```
Is this intentional?

**Comment by larchunix** [comment]
@f2404: I added this space has been intentionally in 77e6741942dce536e46071e2c2a9cd4f0b37a8eb. I thought it was more consistent with pacman output.

**Comment by f2404** [comment]
@larchunix Yes, I can see your point, thanks.

**Pull request merged**
